server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # 🚨 Vital: Redirige cualquier ruta no encontrada al index.html
        try_files $uri $uri/ /index.html;
    }
}