sonar.projectKey=front-tienda-pedidos
sonar.projectName=Front Tienda Pedidos
sonar.projectVersion=1.0

# Rutas de código y pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=node_modules/**, dist/**, src/assets/**

# Reporte de cobertura para Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json